all:
  src/ext/inflector.js
  src/ext/md5.js
  src/ext/shortcut.js
  src/ext/keyboard_1_49.js
  src/tr8n.js
  src/logger.js
  src/cookie.js
  src/event.js
  src/utils.js
  src/effects.js
  src/sdk/request.js
  src/sdk/api.js
  src/sdk/auth.js
  src/sdk/proxy.js
  src/sdk/language.js
  src/sdk/translation_key.js
  src/sdk/translation.js
  src/sdk/tokens/base.js
  src/sdk/tokens/data_token.js
  src/sdk/tokens/transform_token.js
  src/sdk/tokens/decoration_token.js
  src/sdk/rules/base.js
  src/sdk/rules/date_rule.js
  src/sdk/rules/gender_rule.js
  src/sdk/rules/numeric_rule.js
  src/sdk/rules/list_rule.js
  src/sdk/rules/gender_list_rule.js
  src/sdk/tml/label.js
  src/sdk/tml/token.js
  src/ui/language_selector.js
  src/ui/lightbox.js
  src/ui/translator.js
  src/ui/translation.js
  src/boot.js

ui:
  src/ext/inflector.js
  src/ext/md5.js
  src/ext/shortcut.js
  src/ext/keyboard_1_49.js
  src/tr8n.js
  src/logger.js
  src/cookie.js
  src/event.js
  src/utils.js
  src/effects.js
  src/ui/language_selector.js
  src/ui/lightbox.js
  src/ui/translator.js
  src/ui/translation.js
  src/boot.js

sdk:
  src/ext/inflector.js
  src/ext/md5.js
  src/ext/shortcut.js
  src/ext/keyboard_1_49.js
  src/tr8n.js
  src/logger.js
  src/cookie.js
  src/event.js
  src/utils.js
  src/effects.js
  src/sdk/request.js
  src/sdk/api.js
  src/sdk/auth.js
  src/sdk/proxy.js
  src/sdk/language.js
  src/sdk/translation_key.js
  src/sdk/translation.js
  src/sdk/tokens/base.js
  src/sdk/tokens/data_token.js
  src/sdk/tokens/transform_token.js
  src/sdk/tokens/decoration_token.js
  src/sdk/rules/base.js
  src/sdk/rules/date_rule.js
  src/sdk/rules/gender_rule.js
  src/sdk/rules/numeric_rule.js
  src/sdk/rules/list_rule.js
  src/sdk/rules/gender_list_rule.js
  src/sdk/tml/label.js
  src/sdk/tml/token.js


